### ISSUE TITLE
机器人表情包功能崩溃

### ISSUE THREAD

**Issue by FlakoWESH** [FlakoWESH/AzaleaBot#3]
输入“SNOW MIKU 2017”引发

**Comment by Hatsunespica** [comment]
崩溃信息
```
Traceback (most recent call last):
  File "D:\software\Anaconda3\lib\site-packages\botpy\client.py", line 277, in _run_event
    await coro(*args, **kwargs)
  File "run.py", line 37, in on_message_create
    await message.reply(file_image=sticker)
  File "D:\software\Anaconda3\lib\site-packages\botpy\message.py", line 84, in reply
    return await self._api.post_message(channel_id=self.channel_id, msg_id=self.id, **kwargs)
  File "D:\software\Anaconda3\lib\site-packages\botpy\api.py", line 502, in post_message
    with open(file_image, "rb") as img:
PermissionError: [Errno 13] Permission denied: 'util/SNOW MIKU 2017&Yukine(HATSUNE MIKU)_4994420_sticker/PNG'
```

**Comment by Hatsunespica** [comment]
bug是来自于没有对获取的文件是表情包还是文件夹进行区分。
已经在 6847969d1adfa9b70e1ae080b58fa97c7bc0af6a commit里进行修复
